import Head from "next/head";

import styles from "@/styles/Home.module.css";

import { LoginForm } from "@/containers";
import { ContentWrapper } from "@/compnents";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen">
        <ContentWrapper>
          <div className="flex h-full mt-auto mb-auto">
            <LoginForm />
          </div>
        </ContentWrapper>
      </main>
    </>
  );
}
